# Generated by Django 5.0.2 on 2024-03-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['feita']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='feita',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='titulo',
        ),
    ]
